[package]
name = "dimmac"
version = "0.1.0"
edition = "2021"
description = ""
license = "MIT OR Apache-2.0"
authors = [
    "Taennan taennan@zohomail.com"
]
repository = ""
exclude = [".idea", ".git", ".gitignore", "CHANGELOG.md"]

keywords = ["multidimensional", "macros"]
categories = []
